// Topic-5-Frameworks/React/3/src/Components/MovieEdit/MovieEdit.js
import React, { useState } from "react";
import { withRouter } from "react-router-dom";
import "./MovieEdit.scss";
import MoviesService from "Services/movies";
import Movie from "Models/movie";

function MovieEdit({ history, movie }) {
  const [duration, setDuration] = useState(movie.duration);
  const [title, setTitle] = useState(movie.title);
  const [year, setYear] = useState(movie.year);

  const goBack = () => {
    history.goBack();
  };

  const updateMovie = event => {
    event.preventDefault();
    MoviesService.updateMovie(
      movie.id,
      new Movie(title, year || "", duration || "")
    );
    goBack();
  };

  const updateMovieDuration = ({ target: { value: duration } }) =>
    setDuration(duration);
  const updateMovieTitle = ({ target: { value: title } }) => setTitle(title);
  const updateMovieYear = ({ target: { value: year } }) => setYear(year);

  return (
    <form onSubmit={updateMovie}>
      <div>
        <label htmlFor="title">Title: </label>
        <input
          // Since useState is async, movie.title is used as fallback.
          value={title || movie.title}
          type="text"
          onChange={updateMovieTitle}
          required
          name="title"
          id="title"
        />
      </div>
      <div>
        <label htmlFor="year">Year: </label>
        <input
          value={year || movie.year}
          type="number"
          onChange={updateMovieYear}
          name="year"
          min="1878"
          max={new Date().getFullYear()}
          id="year"
        />
      </div>
      <div>
        <label htmlFor="duration">Duration: </label>
        <input
          value={duration || movie.duration}
          type="time"
          onChange={updateMovieDuration}
          name="duration"
          id="duration"
        />
      </div>
      <button type="submit">Update movie</button>
      <button onClick={goBack}>Cancel</button>
    </form>
  );
}

export default withRouter(MovieEdit);

// Topic-5-Frameworks/Angular/3/src/app/components/movie-edit/movie-edit.component.ts
import { Component, OnInit } from "@angular/core";
import { ActivatedRoute, Router } from "@angular/router";
import { MoviesService } from "src/app/services/movies.service";

@Component({
  selector: "movie-edit",
  templateUrl: "./movie-edit.component.html",
  styleUrls: ["./movie-edit.component.scss"]
})
export class MovieEditComponent implements OnInit {
  movie: Object;
  movieID = Number(this.route.snapshot.params.id);

  constructor(
    private router: Router,
    private route: ActivatedRoute,
    private moviesService: MoviesService
  ) {}

  goBack() {
    this.router.navigate([`/movie/${this.movieID}`]);
  }

  async updateMovie() {
    await this.moviesService.updateMovie(this.movieID, this.movie);
    this.goBack();
  }

  ngOnInit() {
    this.movie = this.route.snapshot.data.movie;
  }
}

<form #movieEditForm="ngForm" (ngSubmit)="updateMovie()">
  <div>
    <label for="title">Title: </label>
    <input
      type="text"
      required
      [(ngModel)]="movie.title"
      name="title"
      id="title"
    />
  </div>
  <div>
    <label for="year">Year: </label>
    <input type="number" [(ngModel)]="movie.year" name="year" id="year" />
  </div>
  <div>
    <label for="duration">Duration: </label>
    <input
      type="time"
      [(ngModel)]="movie.duration"
      name="duration"
      id="duration"
    />
  </div>
  <button type="submit">Update movie</button>
  <button (click)="goBack()">Cancel</button>
</form>
